### ISSUE TITLE
windows platform error

### ISSUE THREAD

**Issue by Whatguia** [miguelcastillon/lnrr#4]
Hello, I am compiling on the windows platform, and the following problems occur. It seems that there is something wrong with your code. For example, the last three errors are "fgt::Transform::compute": No overloaded function accepts 3 parameters, this function Can only receive 2 parameters, you passed three

**Comment by miguelcastillon** [comment]
LNRR depends on this fork of the fgt library: https://github.com/miguelcastillon/fgt_threshold

**Comment by Whatguia** [comment]
still not work  plz check https://github.com/miguelcastillon/fgt_threshold/issues/1

**Comment by Whatguia** [comment]
By the way, I used the official fgt to tune through, but the compute P function is too slow, so I still want to try your ScanToModel::computeP_FGT() function, but miguelcastillon/fgt_threshold cant work
